### ISSUE TITLE
Public Repository

### ISSUE THREAD

**Issue by vmitchell85** [carlosdevletian/calculadora-hai#1]
Hello there,

I was browsing github and noticed this repository isn't private and you've included the Nova code. Since it's against the Nova terms to have it public I figured I'd create an issue to let you know.

Happy Coding!
- Vince

**Comment by carlosdevletian** [comment]
Thanks for letting me know!

I removed it already.

**Comment by vmitchell85** [comment]
You might also want to remove it from git history, as it's still accessible in previous commits:

https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

😄

**Comment by carlosdevletian** [comment]
All done! Thanks for the heads up
